# Generated by Django 5.0.6 on 2025-08-28 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BodyType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=120, unique=True)),
            ],
            options={
                "verbose_name": "Body type",
                "verbose_name_plural": "Body types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Make",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=120, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("model_name", models.CharField(blank=True, max_length=120)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "mileage",
                    models.PositiveIntegerField(
                        blank=True, help_text="Miles", null=True
                    ),
                ),
                (
                    "transmission",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Automatic", "Automatic"),
                            ("Manual", "Manual"),
                            ("CVT", "CVT"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "fuel",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Petrol", "Petrol"),
                            ("Diesel", "Diesel"),
                            ("Hybrid", "Hybrid"),
                            ("Electric", "Electric"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "cover",
                    models.ImageField(blank=True, null=True, upload_to="cars/covers/"),
                ),
                ("is_new", models.BooleanField(default=False)),
                ("is_certified", models.BooleanField(default=False)),
                ("is_hot", models.BooleanField(default=False)),
                ("overview", models.TextField(blank=True)),
                ("history", models.TextField(blank=True)),
                ("seller_name", models.CharField(blank=True, max_length=200)),
                ("seller_meta", models.CharField(blank=True, max_length=200)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "body_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cars",
                        to="models.bodytype",
                    ),
                ),
                (
                    "make",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cars",
                        to="models.make",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="CarImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="cars/gallery/")),
                ("alt", models.CharField(blank=True, max_length=200)),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="models.car",
                    ),
                ),
            ],
        ),
    ]
