# Generated by Django 5.0.6 on 2025-08-28 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("models", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="is_featured",
            field=models.BooleanField(
                default=False, help_text="Show this car in the Featured section"
            ),
        ),
    ]
