# Generated by Django 5.0.6 on 2025-08-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("models", "0002_car_is_featured"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeroSlide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("subtitle", models.CharField(blank=True, max_length=300)),
                ("image", models.ImageField(upload_to="hero/")),
                ("is_active", models.BooleanField(default=True)),
                ("ordering", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["ordering"],
            },
        ),
    ]
