# Generated by Django 5.0.6 on 2025-08-28 18:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("models", "0003_heroslide"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="heroslide",
            name="subtitle",
        ),
        migrations.RemoveField(
            model_name="heroslide",
            name="title",
        ),
    ]
