# Generated by Django 5.0.6 on 2025-08-30 19:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("models", "0005_testdriverequest"),
    ]

    operations = [
        migrations.RenameField(
            model_name="testdriverequest",
            old_name="notes",
            new_name="message",
        ),
        migrations.RemoveField(
            model_name="testdriverequest",
            name="handled",
        ),
        migrations.RemoveField(
            model_name="testdriverequest",
            name="user",
        ),
        migrations.AddField(
            model_name="car",
            name="seller_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="testdriverequest",
            name="seller_email_snapshot",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="testdriverequest",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="testdriverequest",
            name="preferred_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
