# Generated by Django 5.0.6 on 2025-09-03 06:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("models", "0008_carreview_alter_reviewfeedback_review_delete_review"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="carreview",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Car review",
                "verbose_name_plural": "Car reviews",
            },
        ),
        migrations.AddIndex(
            model_name="carreview",
            index=models.Index(
                fields=["car", "status"], name="models_carr_car_id_768604_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="carreview",
            index=models.Index(
                fields=["car", "created_at"], name="models_carr_car_id_aa60d0_idx"
            ),
        ),
    ]
