# Generated by Django 5.0.6 on 2025-09-03 06:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("models", "0009_alter_carreview_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="reviewfeedback",
            old_name="created",
            new_name="created_at",
        ),
        migrations.AlterUniqueTogether(
            name="reviewfeedback",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="reviewfeedback",
            name="action",
            field=models.CharField(
                choices=[("helpful", "Helpful"), ("report", "Report")], max_length=7
            ),
        ),
        migrations.AddConstraint(
            model_name="reviewfeedback",
            constraint=models.UniqueConstraint(
                fields=("review", "user", "action"),
                name="uniq_feedback_per_user_per_action",
            ),
        ),
    ]
