# Generated by Django 5.0.6 on 2025-09-03 09:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("models", "0010_rename_created_reviewfeedback_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="seller_image",
            field=models.ImageField(blank=True, null=True, upload_to="profiles/"),
        ),
        migrations.AddField(
            model_name="car",
            name="seller_phone",
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
