# Generated by Django 5.0.6 on 2025-09-07 18:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("models", "0011_car_seller_image_car_seller_phone"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="car",
            options={
                "ordering": ["-created"],
                "verbose_name": "Car",
                "verbose_name_plural": "Cars",
            },
        ),
        migrations.AlterField(
            model_name="car",
            name="fuel",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Petrol", "Petrol"),
                    ("Diesel", "Diesel"),
                    ("Hybrid", "Hybrid"),
                    ("Electric", "Electric"),
                ],
                max_length=20,
                verbose_name="Fuel",
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="history",
            field=models.TextField(blank=True, verbose_name="History"),
        ),
        migrations.AlterField(
            model_name="car",
            name="is_certified",
            field=models.BooleanField(default=False, verbose_name="Certified"),
        ),
        migrations.AlterField(
            model_name="car",
            name="is_featured",
            field=models.BooleanField(
                default=False,
                help_text="Show this car in the Featured section",
                verbose_name="Featured",
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="is_hot",
            field=models.BooleanField(default=False, verbose_name="Hot"),
        ),
        migrations.AlterField(
            model_name="car",
            name="is_new",
            field=models.BooleanField(default=False, verbose_name="New"),
        ),
        migrations.AlterField(
            model_name="car",
            name="mileage",
            field=models.PositiveIntegerField(
                blank=True, help_text="Miles", null=True, verbose_name="Mileage"
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="model_name",
            field=models.CharField(blank=True, max_length=120, verbose_name="Model"),
        ),
        migrations.AlterField(
            model_name="car",
            name="overview",
            field=models.TextField(blank=True, verbose_name="Overview"),
        ),
        migrations.AlterField(
            model_name="car",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Price",
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="seller_email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="Seller email"
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="seller_meta",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Seller info"
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="seller_name",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Seller name"
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="seller_phone",
            field=models.CharField(
                blank=True, max_length=32, verbose_name="Seller phone"
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="car",
            name="transmission",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Automatic", "Automatic"),
                    ("Manual", "Manual"),
                    ("CVT", "CVT"),
                ],
                max_length=20,
                verbose_name="Transmission",
            ),
        ),
    ]
