# Generated by Django 5.0.6 on 2025-09-09 09:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("models", "0012_alter_car_options_alter_car_fuel_alter_car_history_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="seller_address",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Seller address"
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="seller_lat",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="e.g. 40.712776",
                max_digits=9,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-90),
                    django.core.validators.MaxValueValidator(90),
                ],
                verbose_name="Seller latitude",
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="seller_lng",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="e.g. -74.005974",
                max_digits=9,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-180),
                    django.core.validators.MaxValueValidator(180),
                ],
                verbose_name="Seller longitude",
            ),
        ),
        migrations.AddIndex(
            model_name="car",
            index=models.Index(
                fields=["seller_lat", "seller_lng"],
                name="models_car_seller__cf2b0e_idx",
            ),
        ),
    ]
