# Generated by Django 5.0.6 on 2025-10-04 17:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0003_order_gateway_response_order_order_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="refund_amount",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="order",
            name="refund_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="refund_response",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="refund_status",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="order",
            name="refunded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("canceled", "Canceled"),
                    ("failed", "Failed"),
                    ("refunded", "Refunded"),
                ],
                default="pending",
                max_length=12,
            ),
        ),
    ]
