# Generated by Django 5.0.6 on 2025-08-31 20:06

import django.db.models.deletion
import marketplace.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CarListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("make", models.CharField(max_length=80)),
                ("model", models.CharField(max_length=80)),
                ("year", models.PositiveIntegerField()),
                ("mileage_km", models.PositiveIntegerField(default=0)),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("used", "Used"),
                            ("certified", "Certified Pre-Owned"),
                        ],
                        default="used",
                        max_length=12,
                    ),
                ),
                (
                    "transmission",
                    models.CharField(
                        choices=[
                            ("auto", "Automatic"),
                            ("manual", "Manual"),
                            ("cvt", "CVT"),
                            ("other", "Other"),
                        ],
                        default="auto",
                        max_length=10,
                    ),
                ),
                (
                    "fuel_type",
                    models.CharField(
                        choices=[
                            ("petrol", "Petrol"),
                            ("diesel", "Diesel"),
                            ("hybrid", "Hybrid"),
                            ("electric", "Electric"),
                            ("cng", "CNG"),
                            ("other", "Other"),
                        ],
                        default="petrol",
                        max_length=12,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("description", models.TextField(blank=True)),
                ("location", models.CharField(blank=True, max_length=120)),
                ("contact_phone", models.CharField(blank=True, max_length=30)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("is_published", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(blank=True, max_length=180, unique=True)),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="car_listings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CarPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to=marketplace.models.listing_upload_path),
                ),
                ("alt_text", models.CharField(blank=True, max_length=120)),
                ("is_cover", models.BooleanField(default=False)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="marketplace.carlisting",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_cover", "-uploaded_at"],
            },
        ),
    ]
