# Generated by Django 5.0.6 on 2025-09-03 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0002_sellerprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="sellerprofile",
            name="address_line1",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="city",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="country",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="dealer_license",
            field=models.FileField(blank=True, null=True, upload_to="kyc/"),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="dealership_name",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="id_document",
            field=models.FileField(blank=True, null=True, upload_to="kyc/"),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="postal_code",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="state",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="tax_id",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="terms_accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="verification_status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("PENDING", "Pending review"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                ],
                default="DRAFT",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="whatsapp",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
