# Generated by Django 5.0.6 on 2025-09-04 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0004_savedsearch"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedsearch",
            name="query_json",
            field=models.JSONField(default=dict),
        ),
    ]
