# Generated by Django 5.0.6 on 2025-09-07 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0006_alter_sellerprofile_user_seller_and_more"),
        ("models", "0012_alter_car_options_alter_car_fuel_alter_car_history_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedSearchHit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("notified", models.BooleanField(default=True)),
                (
                    "last_seen_car_created_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="models.car"
                    ),
                ),
                (
                    "saved_search",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hits",
                        to="marketplace.savedsearch",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["saved_search", "created_at"],
                        name="marketplace_saved_s_1612fb_idx",
                    )
                ],
                "unique_together": {("saved_search", "car")},
            },
        ),
    ]
