# Generated by Django 5.0.6 on 2025-09-08 11:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0009_cart_cartitem_order_orderitem"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together={("cart", "car")},
        ),
    ]
