# Generated by Django 5.0.6 on 2025-09-08 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0010_alter_cartitem_unique_together"),
        ("models", "0012_alter_car_options_alter_car_fuel_alter_car_history_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="car",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="models.car"
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="car",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="models.car"
            ),
        ),
    ]
