# Generated by Django 5.0.6 on 2025-09-08 15:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0011_alter_cartitem_car_alter_orderitem_car"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together=set(),
        ),
    ]
